### ISSUE TITLE
Revo 2.2 compatibility

### ISSUE THREAD

**Issue by FickleLife** [benjamin-vauchel/SuperBoxSelect#1]
Any manager page with a SuperBoxSelect tv attached to it crashes with this message: 

Fatal error: Call to undefined method modTemplateVarInputRenderDeprecated::processBindings() in /home/centurio/public_html/core/model/modx/processors/element/tv/renders/mgr/input/superboxselect.php on line 14

**Comment by benjamin-vauchel** [comment]
It's weird. The processBindings function is still used by the listbox TV in Revo 2.2-rc1. Do you get the same message if you use a multiple listbox instead of SuperBoxSelect ?

**Comment by benjamin-vauchel** [comment]
I got it. In the develop branch, the TV input and output renders changed (https://github.com/modxcms/revolution/blob/d4d94137a5518cbb30b8fbf3a0419f05f0b32112/core/model/modx/processors/element/tv/renders/mgr/input/listbox-multiple.class.php). I'll fix that soon.
Thanks.

**Comment by FickleLife** [comment]
Great - thanks

**Comment by benjamin-vauchel** [comment]
SuperBoxSelect 1.0.1-rc1 refactored for MODx Revo 2.2 : http://modx.com/extras/package/superboxselect
