### ISSUE TITLE
Install doesn't respect non-standard manager name (Revo 2.2.0-pl2)

### ISSUE THREAD

**Issue by westport** [benjamin-vauchel/SuperBoxSelect#4]
As per MODx Security Hardening standards, I have changed the name of my manager directory.  However, it seems that the "element/tv/renders/input/superboxselect.tpl" is saved to the default "manager" directory.  So, when attempting to edit a page using the TV, the following error appears in the PHP error log (the manager errors out)

From PHP Error log:

PHP Fatal error:  Uncaught exception 'SmartyException' with message 'Unable to load template file 'element/tv/renders/input/superboxselect.tpl'' in <path to core>/model/smarty/sysplugins/smarty_internal_template.php:162
Stack trace:
#0 <path to core>/model/smarty/sysplugins/smarty_internal_template.php(537): Smarty_Internal_Template->isExisting(true)
#1 <path to core>/model/smarty/Smarty.class.php(335): Smarty_Internal_Template->getRenderedTemplate()
#2 <path to core>/model/modx/modmanagercontroller.class.php(252): Smarty->fetch('element/tv/rend...')
#3 <path to core>/model/modx/modtemplatevar.class.php(1103): modManagerController->fetchTemplate('element/tv/rend...')
#4 <path to core>/model/modx/modtemplatevar.class.php(421): modTemplateVarInputRender->render('437', Array)
#5 <path to core>/model/modx/modtemplatevar.class.php(366): modTemplateVar->getRend in <path to core>/model/smarty/sysplugins/smarty_internal_template.php on line 162

After copying the file to the correct location, all is well.

**Comment by benjamin-vauchel** [comment]
Thanks for the report! 
It's fixed in SuperBoxSelect 1.0.1-rc2.

**Comment by westport** [comment]
Thanks so much.  This was my first bit of code feedback, so I hope it was helpful.  I'm trying to be better at helping out those who have helped me out so much.

This addon is exactly what I've been needing for such a long time.  Great interface, well done!

Ryan Thompson
Multimedia Manager  |  Westport Innovations Inc.
604-718-8305  |  rthompson@westport.com
www.westport.com

-----Original Message-----
